title: RHUL CS Seminars
domain: rhul-cs-seminars.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://rhul-cs-seminars.github.io  # the base hostname and protocol for your site, e.g. http://example.com
email: anand.subramoney@rhul.ac.uk 

term: Autumn 25/26

exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - misc

collections_dir: seminars

collections:
  autumn_25:
    order: 1
    name: "Autumn 2025"
  summer_25:
    order: 2
    name: "Summer 2025"
  spring_25:
    order: 3
    name: "Spring 2025"
  autumn_24:
    order: 4
    name: "Autumn 2024"
  spring_24:
    order: 5
    name: "Spring 2024"
  autumn_23:
    order: 6
    name: "Autumn 2023"


# autoprefixer:
#   browsers:
#     - last 4 versions

